# general settings
include         "system.in.init"

# read topology/restart files
read_data       "system_after_nvt.data"
#read_restart	"restart.*.npt"

# read force field settings and groups
include         system.in.settings

# define additional groups
group           mobile subtract all CghostGraphene CghostGrapheneTop Cgraphene #CgrapheneTop
group		topGraphene type 12 13 

# set up trajectory file
dump            1 all custom 10000 traj_comp.lammpstrj id mol type x y z ix iy iz

# fix smooth walls
fix zwalls all wall/reflect zlo 0 zhi 100

# fix polarizable molecule bonds
fix 1 water shake 0.0001 20 1000 b 2

# exclude ghost graphene interactions
neigh_modify exclude type 4 4
neigh_modify exclude type 9 9
neigh_modify exclude type 4 9
neigh_modify exclude type 12 12
neigh_modify exclude type 13 13
neigh_modify exclude type 12 13

# setting top graphene layer velocity to zero
velocity topGraphene zero angular
velocity topGraphene zero linear
run 0

# thermostatting the first bead in the lipid chain (bond to ghost graphene)
fix fxlng thermoFA langevin 298.15 298.15 100.0 699483 zero yes

#1GPa = 0.14393 kcal mol-1 A-3, 1atm = 0.0000145837 kcal mol-1 A-3, kcal mol-1 A-3 x A2 = kcal mol-1 A-1
variable        applied_press equal 100                                                    #pressure in atm
variable        Sz       equal 119.112*103.154*4                         
print            "Surface Area = ${Sz} A^2"
variable        applied_force equal (${applied_press}*0.0000145837*${Sz})                       #in kcal mol-1 A-1 (/2 if applied to both surfaces)
print            "Applied Force = ${applied_force} kcal mol^-1 A^-1" 

variable        z_force_top   equal (-${applied_force})/(count(CgrapheneTop))
print            "z_force_top = ${z_force_top} kcal mol-1 A-1"

fix fxTop CgrapheneTop setforce 0 0 NULL
fix forceTop CgrapheneTop aveforce NULL NULL v_z_force_top
fix fxlan1 CghostGrapheneTop rigid single force * off off on torque * off off off #langevin 0.0 0.0 1000000.0 24526
fix fxTopCouple CgrapheneTop spring couple CghostGrapheneTop 1000000 NULL NULL 0.0 0.0

# lower surface
velocity CghostGraphene set 0 0 0
velocity Cgraphene set 0 0 0
fix freeze1 CghostGraphene setforce 0.0 0.0 0.0
fix freeze2 Cgraphene setforce 0.0 0.0 0.0

# output contact thickness
compute topCOM 	CgrapheneTop com
compute botCOM 	Cgraphene com
variable thickness equal c_topCOM[3]-c_botCOM[3] 
fix             thickness_ave all ave/time 1 10000 10000 v_thickness file thickness_ave

# integrate the equations of motion
fix fxnve mobile nve

compute tempMobile mobile temp
compute pressMobile all pressure tempMobile

thermo_style    custom step c_tempMobile pe etotal press vol epair #c_pressMobile vol epair
thermo          100  # time interval for printing out "thermo" data

restart		50000 restart.*.npt

timestep        5.0
run		1000000 upto

write_data  	system_after_comp.data
